version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - ${IP}:3306:3306
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER_NAME}"
      MYSQL_PASSWORD: "${DB_USER_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    volumes:
      - ./wp-data/:/docker-entrypoint-initdb.d/

  wp:
    image: wordpress
    depends_on:
      - db
    restart: always
    ports:
      - ${IP}:80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: "${DB_USER_NAME}"
      WORDPRESS_DB_PASSWORD: "${DB_USER_PASSWORD}"
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_HOME', 'http://localhost' );
        define( 'WP_SITEURL', 'http://localhost' );
    volumes:
      - type: bind
        source: ${PWD}/config/php/uploads.ini
        target: /usr/local/etc/php/conf.d/uploads.ini
      - ./nillkizz-abooks/:/var/www/html/wp-content/plugins/nillkizz-abooks/

  pma:
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - ${IP}:8081:80
    environment:
      PMA_USER: root
      PMA_PASSWORD: "${DB_ROOT_PASSWORD}"
    volumes:
      - type: bind
        source: ${PWD}/config/php/uploads.ini
        target: /usr/local/etc/php/conf.d/uploads.ini
